### ISSUE TITLE
[Meta] OKHttp Client implementation

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/okhttp-client-adapter#1]
This is a parent ticket for the implementation of the OkHttpClient implementation. The action items are as follows;-

- [x] #2
- [x] #5
- [x] Vet Naming and related inner documentation of classes
- [x] Update ReadMe when Classes become stable
- [x] #3
- [x] Add CD workflow for package publishing

**Comment by sufyankhanrao** [comment]
Closing this tracker issue as all sub-tasks are done.
